<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23" started-at="2014-07-31T10:13:29Z" finished-at="2014-07-31T10:13:29Z">
    <groups>
      <group name="Functionaltest">
        <method signature="TestIcici.testOne(java.lang.String, java.lang.String)[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="testOne" class="com.icici.automation.TestIcici"/>
      </group> <!-- Functionaltest -->
      <group name="activationtest">
        <method signature="TestIcici.testTwo()[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="testTwo" class="com.icici.automation.TestIcici"/>
      </group> <!-- activationtest -->
      <group name="usabilitytest">
        <method signature="TestIcici.testThree()[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="testThree" class="com.icici.automation.TestIcici"/>
      </group> <!-- usabilitytest -->
    </groups>
    <test name="Default test" duration-ms="23" started-at="2014-07-31T10:13:29Z" finished-at="2014-07-31T10:13:29Z">
      <class name="com.icici.automation.TestIcici">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="setUp" is-config="true" duration-ms="0" started-at="2014-07-31T15:43:29Z" finished-at="2014-07-31T15:43:29Z">
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.40.0', revision: '4c5c0568b004f67810ee41c459549aa4b09c651e', time: '2014-02-19 11:13:01'
System info: host: 'AIPLBNGG-VAP.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.8.0_05'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.40.0', revision: '4c5c0568b004f67810ee41c459549aa4b09c651e', time: '2014-02-19 11:13:01'
System info: host: 'AIPLBNGG-VAP.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.8.0_05'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:113)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at com.icici.automation.IciciBase.setUp(IciciBase.java:109)
	at com.icici.automation.TestIcici.setUp(TestIcici.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.HttpCommandExecutor.fallBackExecute(HttpCommandExecutor.java:319)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:298)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:546)
	... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testOne(java.lang.String, java.lang.String)[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="testOne" duration-ms="1" started-at="2014-07-31T15:43:29Z" data-provider="iciciInvaliddata" finished-at="2014-07-31T15:43:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1245]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="SKIP" signature="testThree()[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="testThree" duration-ms="1" started-at="2014-07-31T15:43:29Z" finished-at="2014-07-31T15:43:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="FAIL" signature="testTwo()[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="testTwo" duration-ms="3" started-at="2014-07-31T15:43:29Z" data-provider="iciciValiddata" finished-at="2014-07-31T15:43:29Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 2 parameters but the method com.icici.automation.TestIcici#testTwo takes 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 2 parameters but the method com.icici.automation.TestIcici#testTwo takes 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1337)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.icici.automation.TestIcici@7c0e2abd]" name="tearDown" is-config="true" duration-ms="0" started-at="2014-07-31T15:43:30Z" finished-at="2014-07-31T15:43:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.icici.automation.TestIcici -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
